config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'pages/home'

  get 'pages/commercial'

  get 'pages/residential'

  get 'pages/contactus'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def commercial
  end

  def residential
  end

  def contactus
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awning</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:3;width:250px" id="mySidebar">
      <div class="w3-container w3-display-container w3-padding-16">
        <h3 class="w3-wide">
          <%= link_to root_path do %>
          <%= image_tag "logo1.png", :style => "width:100%" %>
          <%end%>
        </h3>
      </div>
      <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">
        <%= link_to root_path do %><p class="w3-bar-item w3-button">
          HOME
        </p><%end%>
        <a onclick="myAccFunc()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" >
          Commercials <i class="fa fa-caret-down"></i>
        </a>
          <div id="demoAcc" class="w3-bar-block w3-hide w3-padding-large w3-medium">
            <a href="#" class="w3-bar-item w3-button ">Commercial Awnings</a>
            <a href="#" class="w3-bar-item w3-button">Metal Drive-Thru & Entrance Canopies</a>
            <a href="#" class="w3-bar-item w3-button">Drive-Thru Order Board Canopies</a>
            <a href="#" class="w3-bar-item w3-button">Cupola Tower Peaks</a>
            <a href="#" class="w3-bar-item w3-button">Kiosk Canopies</a>
            <a href="#" class="w3-bar-item w3-button">Backlit Canopies</a>
            <a href="#" class="w3-bar-item w3-button">Trellises</a>
            <a href="#" class="w3-bar-item w3-button">Sunshade Louvers</a>
            <a href="#" class="w3-bar-item w3-button">LED Channel Letter Signs</a>
            <a href="#" class="w3-bar-item w3-button">Illuminated Signs</a>
            <a href="#" class="w3-bar-item w3-button">Fascia Wall Signs</a>
            <a href="#" class="w3-bar-item w3-button">Pylon & Monument Signs</a>
            <a href="#" class="w3-bar-item w3-button">Up/Down Light Band</a>
            <a href="#" class="w3-bar-item w3-button">Up Light Box</a>
            <a href="#" class="w3-bar-item w3-button">Roof Access Ladders</a>
            <a href="#" class="w3-bar-item w3-button">LED Border Tube Lighting</a>

          </div>
        <%= link_to pages_residential_path do %><p  class="w3-bar-item w3-button">
          Residential</p>
        <%end%>
        <a href="#footer" class="w3-bar-item w3-button">Contact Us</a>
      </div>
    <!--  <a href="#footer" class="w3-bar-item w3-button w3-padding">Contact</a>
      <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding" onclick="document.getElementById('newsletter').style.display='block'">Newsletter</a>
      <a href="#footer"  class="w3-bar-item w3-button w3-padding">Subscribe</a>
    -->
    </nav>

    <!-- Top menu on small screens -->
    <header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
      <div class="w3-bar-item w3-padding-24 w3-wide"><%= image_tag "logo1.png", :style => "width:100%" %></div>
      <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    </header>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:250px">

      <!-- Push down content on small screens -->
      <div class="w3-hide-large" style="margin-top:100px"></div>

        <!-- Top header -->
        <header class="w3-container w3-xlarge">
          <p class="w3-left"><%=yield(:title)%></p>
        <!--  <p class="w3-right">
            <i class="fa fa-shopping-cart w3-margin-right"></i>
            <i class="fa fa-search"></i>
          </p>
        -->
        </header>


        <script>
        // Accordion
        function myAccFunc() {
            var x = document.getElementById("demoAcc");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }

        // Click on the "Jeans" link on page load to open the accordion for demo purposes
        //document.getElementById("myBtn").click();


        // Script to open and close sidebar
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("myOverlay").style.display = "block";
        }

        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("myOverlay").style.display = "none";
        }
        </script>





    <%= yield %>
    <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
      <div class="w3-row">
        <div class="w3-third w3-container w3-padding-16">
      <!--<div class="w3-row-padding">
        <div class="w3-col s4">-->
          <h4>Contact</h4>
          <p>Questions? Go ahead.</p>
          <form action="/action_page.php" target="_blank">
            <p><input class="w3-input w3-border" type="text" placeholder="Name" name="Name" required></p>
            <p><input class="w3-input w3-border" type="text" placeholder="Email" name="Email" required></p>
            <p>
              <select class="w3-select" name="Subject" required>
                <option value="" disabled selected>Choose your subject</option>
                <option value="1">Drive-Thru</option>
                <option value="2">Commercial</option>
                <option value="3">Residential</option>
                <option value="4">General</option>
                <option value="5">Question</option>
              </select>
            </p>
            <p><input class="w3-input w3-border" type="integer" placeholder="Phone Number" name="PhoneNumber" required></p>
            <p><input class="w3-input w3-border" type="text" placeholder="Best time to call" name="BestTimeToCall" required></p>
            <p><input class="w3-input w3-border" type="text" placeholder="Address" name="Address" required></p>
            <p><input class="w3-input w3-border" type="text" placeholder="City, State, ZIP" name="CıtyStateZip" required></p>
            <p><input class="w3-input w3-border" type="text" placeholder="Message" name="Message" required></p>
            <button type="submit" class="w3-button w3-block w3-black">Send</button>
          </form>
        </div>

        <div class="w3-third w3-container w3-padding-16">
        <!--<div class="w3-col s4">-->
          <h4>Optional Installation Services</h4>
          <p><a href="#">Installation of all our products is largely expedited by our experienced crews. They deliver the products to the site, complete with all components and the necessary tools and equipment, to finish the project in the shortest possible time frame.</a></p>

        </div>

        <div class="w3-third w3-container w3-padding-16">
        <!--<div class="w3-col s4 w3-justify">-->
          <h4>Store</h4>
          <p><i class="fa fa-fw fa-map-marker"></i> 3265 Highway 62 NW,
  Corydon, IN, 47112-6709, USA</p>
          <p><i class="fa fa-fw fa-phone"></i> Tel No: (812) 734-0423
  Fax No: (812) 734-0344</p>
          <p><i class="fa fa-fw fa-envelope"></i>sales@awningtecusa.com</p>
          <h4 class="w3-padding-16">We accept</h4>
          <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
          <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
          <br>
          <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
          <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
          <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
          <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
          <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
          <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/pages/commercial.html.erb
<h1>Pages#commercial</h1>
<p>Find me in app/views/pages/commercial.html.erb</p>

app/views/pages/contactus.html.erb
<h1>Pages#contactus</h1>
<p>Find me in app/views/pages/contactus.html.erb</p>

app/views/pages/hhome.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title>Basic 87</title>
<meta charset="iso-8859-1">
<link rel="stylesheet" href="styles/layout.css" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<!--[if lt IE 9]><script src="scripts/html5shiv.js"></script><![endif]-->
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <div id="hgroup">
      <article class="one_quarter">
        <figure><%= image_tag "logo1.png" %>

        </figure>
      </article>
      <img src="app\assets\images\logo1.png" width="215" height="315" alt="">
    </div>
    <nav>
      <ul>
        <li><a href="pages/home">Home</a></li>
        <li><a href="pages/commercial">Commercial</a></li>
        <li><a href="pages/residential">Residential</a></li>
        <li class="last"><a href="pages/contactus">Contact Us</a></li>
      </ul>
    </nav>
  </header>
</div>
<!-- content -->
<div class="wrapper row2">
  <div id="container" class="clear">
    <!-- content body -->
    <div id="homepage">
      <!-- One Quarter -->
      <section id="latest" class="clear">
        <div class="w3-content w3-section" style="max-width:500px">
          <p>The w3-animate-fading class animates an element in and out (takes about 10 seconds).</p>
          <p><%= link_to root_path do %>
            <%= image_tag "backlitCanopies.jpg", :class => "mySlides w3-animate-fading" %>
            <%= image_tag "driveThruOB.jpg", :class => "mySlides w3-animate-fading" %>
            <%= image_tag "lightband.jpg", :class => "mySlides w3-animate-fading" %>
            <%= image_tag "sunshadeLouver.jpg", :class => "mySlides w3-animate-fading" %>
            <% end %>
          </p>
          </div>
      </section>

<script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}
    x[myIndex-1].style.display = "block";
    setTimeout(carousel, 9000);
}
</script>
      <!-- / One Quarter -->
      <section id="shout">
        <p>Vestibulumaccumsan egestibulum eu justo convallis augue estas aenean elit intesque sed. Facilispede estibulum nulla orna nisl velit elit ac aliquat non tincidunt. Namjusto cras urna urnaretra lor urna neque sed quis orci nulla laoremut vitae doloreet condimentumst.</p>
      </section>

    <!-- main content -->
    <div id="content">
      <section id="services" class="last clear">
        <ul>
          <li>
            <article class="clear">
              <figure><img src="images/demo/180x150.gif" alt="">
                <figcaption>
                  <h2>Indonectetus facilis leo nibh</h2>
                  <p>This is a W3C compliant free website template from <a href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a>. For full terms of use of this template please read our <a href="http://www.os-templates.com/template-terms">website template licence</a>.</p>
                  <footer class="more"><a href="#">Read More &raquo;</a></footer>
                </figcaption>
              </figure>
            </article>
          </li>
          <li class="last">
            <article class="clear">
              <figure><img src="images/demo/180x150.gif" alt="">
                <figcaption>
                  <h2>Indonectetus facilis leo nibh</h2>
                  <p>You can use and modify the template for both personal and commercial use. You must keep all copyright information and credit links in the template and associated files. For more HTML5 templates visit <a href="http://www.os-templates.com/">free website templates</a>.</p>
                  <footer class="more"><a href="#">Read More &raquo;</a></footer>
                </figcaption>
              </figure>
            </article>
          </li>
        </ul>
      </section>
    </div>
    <!-- right column -->
    <aside id="right_column">
      <h2 class="title">Categories</h2>
      <nav>
        <ul>
          <li><a href="#">Free Website Templates</a></li>
          <li><a href="#">Free CSS Templates</a></li>
          <li><a href="#">Free XHTML Templates</a></li>
          <li><a href="#">Free Web Templates</a></li>
          <li><a href="#">Free Website Layouts</a></li>
          <li><a href="#">Free HTML 5 Templates</a></li>
          <li><a href="#">Free Webdesign Templates</a></li>
          <li><a href="#">Free FireWorks Templates</a></li>
          <li><a href="#">Free PNG Templates</a></li>
          <li class="last"><a href="#">Free Website Themes</a></li>
        </ul>
      </nav>
      <!-- /nav -->
    </aside>
    <!-- / content body -->
  </div>
</div>
<!-- Footer -->
<div class="wrapper row3">
  <footer id="footer" class="clear">
    <p class="fl_left">Copyright &copy; 2012 - All Rights Reserved - <a href="#">Domain Name</a></p>
    <p class="fl_right">Template by <a href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
  </footer>
</div>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<% content_for(:title, "Home")%>
<style>
.w3-sidebar a {font-family: "Roboto", sans-serif}
body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
</style>
<body class="w3-content" style="max-width:1200px">


  <!-- Image header -->
  <div class="w3-display-container w3-container">

                                          <%= link_to root_path do %>
                                            <%= image_tag "logo11.png", :class => "mySlides w3-animate-fading", :alt => "jeans", :style => "width:100%" %>
                                            <%= image_tag "sunshadeLouver.jpg", :class => "mySlides w3-animate-fading", :alt => "jeans", :style => "width:100%" %>
                                            <%= image_tag "lightband.jpg", :class => "mySlides w3-animate-fading", :alt => "jeans", :style => "width:100%" %>
                                            <%= image_tag "backlitCanopies.jpg", :class => "mySlides w3-animate-fading", :alt => "jeans", :style => "width:100%" %>
                                            <%= image_tag "driveThruOB.jpg", :class => "mySlides w3-animate-fading", :alt => "jeans", :style => "width:100%"%>


                                            <% end %>




                                  <script>
                                  var myIndex = 0;
                                  carousel();

                                  function carousel() {
                                    var i;
                                    var x = document.getElementsByClassName("mySlides");
                                    for (i = 0; i < x.length; i++) {
                                       x[i].style.display = "none";
                                    }
                                    myIndex++;
                                    if (myIndex > x.length) {myIndex = 1}
                                    x[myIndex-1].style.display = "block";
                                    setTimeout(carousel, 9000);
                                  }
                                  </script>
<!--    <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">

      <h1 class="w3-jumbo w3-hide-small">New arrivals</h1>
      <h1 class="w3-hide-large w3-hide-medium">New arrivals</h1>
      <h1 class="w3-hide-small">COLLECTION 2016</h1>
      <p><a href="#jeans" class="w3-button w3-black w3-padding-large w3-large">SHOP NOW</a></p>

    </div>-->
  </div>

  <div class="w3-container w3-text-grey" id="jeans">
    <p>(800) 450-4040</p>
  </div>

  <!-- Product grid -->
  <div class="w3-row ">
    <div class="w3-col l3 s6 ">
      <div class="w3-container w3-hover-sepia">
        <%= image_tag "fp_02.jpg", :style => "width:100%" %>

        <p>Drive-Thru<br>
          Order Board Canopies</p>
      </div>
      <div class="w3-container w3-hover-sepia">
        <%= image_tag "fp_03.jpg", :style => "width:100%" %>
        <p>Metal Drive-Thru<br>
          & Entrance Canopies</p>
      </div>
    </div>
    <div class="w3-col l3 s6">
      <div class="w3-container">
        <div class="w3-display-container w3-hover-sepia">
          <%= image_tag "fp_01.jpg", :style => "width:100%" %>
<!--          <span class="w3-tag w3-display-topleft">New</span>
          <div class="w3-display-middle w3-display-hover">
            <button class="w3-button w3-black">Buy now <i class="fa fa-shopping-cart"></i></button>
          </div>
-->
        </div>
        <p>Roof Access<br>
Ladders</p>
      </div>
      <div class="w3-container w3-hover-sepia">
        <%= image_tag "fp_04.jpg", :style => "width:100%" %>
        <p>LED Channel<br>
Letter Signs</p>
      </div>
    </div>

    <div class="w3-col l3 s6">
      <div class="w3-container w3-hover-sepia">
        <%= image_tag "fp_05.jpg", :style => "width:100%" %>
        <p>Commercial<br>
Awnings</p>
      </div>
<!--       <div class="w3-container">
        <div class="w3-display-container">
          <img src="/w3images/jeans4.jpg" style="width:100%">
         <span class="w3-tag w3-display-topleft">Sale</span>
          <div class="w3-display-middle w3-display-hover">
            <button class="w3-button w3-black">Buy now <i class="fa fa-shopping-cart"></i></button>
          </div>

        </div>
        <p>Vintage Skinny Jeans<br><b class="w3-text-red">$14.99</b></p>
      </div>
    </div>

    <div class="w3-col l3 s6">
      <div class="w3-container">
        <img src="/w3images/jeans4.jpg" style="width:100%">
        <p>Vintage Skinny Jeans<br><b>$14.99</b></p>
      </div>
      <div class="w3-container">
        <img src="/w3images/jeans1.jpg" style="width:100%">
        <p>Ripped Skinny Jeans<br><b>$24.99</b></p>
      </div>
-->
    </div>

  </div>

<!--
   Subscribe section
  <div class="w3-container w3-black w3-padding-32">
    <h1>Subscribe</h1>
    <p>To get special offers and VIP treatment:</p>
    <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail" style="width:100%"></p>
    <button type="button" class="w3-button w3-red w3-margin-bottom">Subscribe</button>
  </div>
-->
  <!-- Footer -->

</body>
</html>

app/views/pages/residential.html.erb
<% content_for(:title, "Residential")%>
<style>
.w3-sidebar a {font-family: "Roboto", sans-serif}
body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
</style>

<body>
  <!-- Header -->
  <div class="header">
    <h1>Residential Products</h1>

  </div>

  <!-- Photo Grid -->
  <div class="row">
    <div class="column">
      <%= image_tag "resAwning_01.jpg",:alt => "awning", :style => "width:100%", :class => "w3-hover-sepia cursor", :onclick => "openModal();currentSlide(1)" %>
      <%= image_tag "resAwning_02.jpg",:alt => "awning", :style => "width:100%", :class => "w3-hover-sepia cursor", :onclick => "openModal();currentSlide(2)"  %>
    </div>
    <div class="column">
      <%= image_tag "resAwning_03.jpg",:alt => "awning", :style => "width:100%", :class => "w3-hover-sepia cursor", :onclick => "openModal();currentSlide(3)"  %>
      <%= image_tag "resAwning_05.jpg",:alt => "awning", :style => "width:100%", :class => "w3-hover-sepia cursor", :onclick => "openModal();currentSlide(4)"  %>
    </div>
    <div class="column">
      <%= image_tag "resAwning_06.jpg",:alt => "awning", :style => "width:100%", :class => "w3-hover-sepia cursor", :onclick => "openModal();currentSlide(5)"  %>

    </div>
    <div class="column">
      <%= image_tag "resAwning_04.jpg",:alt => "awning", :style => "width:100%", :class => "w3-hover-sepia cursor", :onclick => "openModal();currentSlide(6)"  %>
    </div>
  </div>
  <div style="margin-bottom: 3em;">
  </div>
  <div id="myModal" class="modal">
      <span class="close cursor" onclick="closeModal()">&times;</span>
      <div class="modal-content">

        <div class="mySlides">
          <div class="numbertext">1 / 6</div>
          <%= image_tag "resAwning_01.jpg",:alt => "awning", :style => "width:100%" %>
        </div>

        <div class="mySlides">
          <div class="numbertext">2 / 6</div>
          <%= image_tag "resAwning_02.jpg",:alt => "awning", :style => "width:100%" %>
        </div>

        <div class="mySlides">
          <div class="numbertext">3 / 6</div>
          <%= image_tag "resAwning_03.jpg",:alt => "awning", :style => "width:100%" %>
        </div>

        <div class="mySlides">
          <div class="numbertext">4 / 6</div>
          <%= image_tag "resAwning_05.jpg",:alt => "awning", :style => "width:100%"%>
        </div>

        <div class="mySlides">
          <div class="numbertext">5 / 6</div>
          <%= image_tag "resAwning_06.jpg",:alt => "awning", :style => "width:100%"%>
        </div>

        <div class="mySlides">
          <div class="numbertext">6 / 6</div>
          <%= image_tag "resAwning_04.jpg",:alt => "awning", :style => "width:100%"%>
        </div>

        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>

        <div class="caption-container">
          <p id="caption"></p>
        </div>


        <div class="column">
          <%= image_tag "resAwning_01.jpg",:alt => "awning", :style => "width:100%", :class => "demo cursor", :onclick => "currentSlide(1)" %>

        </div>
        <div class="column">
          <%= image_tag "resAwning_02.jpg",:alt => "awning", :style => "width:100%", :class => "demo cursor", :onclick => "currentSlide(2)" %>
        </div>
        <div class="column">
          <%= image_tag "resAwning_03.jpg",:alt => "awning", :style => "width:100%", :class => "demo cursor", :onclick => "currentSlide(3)" %>
        </div>
        <div class="column">
          <%= image_tag "resAwning_04.jpg",:alt => "awning", :style => "width:100%", :class => "demo cursor", :onclick => "currentSlide(4)" %>

        </div>
        <div class="column">
          <%= image_tag "resAwning_05.jpg",:alt => "awning", :style => "width:100%", :class => "demo cursor", :onclick => "currentSlide(5)" %>
        </div>
        <div class="column">
          <%= image_tag "resAwning_06.jpg",:alt => "awning", :style => "width:100%", :class => "demo cursor", :onclick => "currentSlide(6)" %>
        </div>
      </div>
    </div>

  </d>
</body>


<style>
body {
  font-family: Verdana, sans-serif;
  margin: 0;
}

* {
  box-sizing: border-box;
}

.row > .column {
  padding: 0 8px;
}

.row:after {
  content: "";
  display: table;
  clear: both;
}

.column {
  float: left;
  width: 25%;
}

/* The Modal (background) */
.modal {
  display: none;
  position: fixed;
  z-index: 3;
  padding-top: 0px;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  overflow: auto;
  background-color: black;
}

/* Modal Content */
.modal-content {
  position: center;
  margin-left: auto;
   margin-right: auto;
  background-color: black;
  padding: 0;
  width: 90%;
  max-width: 1200px;
  height: 800px;
  max-width: 800px;

}

/* The Close Button */
.close {
  color: white;
  position: absolute;
  top: 10px;
  right: 25px;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: #999;
  text-decoration: none;
  cursor: pointer;
}

.mySlides {
  display: none;
}

.cursor {
  cursor: pointer
}

/* Next & previous buttons */
.prev,
.next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 100px;
  margin-top: -100px;
  color: white;
  font-weight: bold;
  font-size: 20px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  user-select: none;
  -webkit-user-select: none;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

.prev {
  left: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover,
.next:hover {
  background-color: rgba(0, 0, 0, 0.8);
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

img {
  margin-bottom: -4px;
}

.caption-container {
  text-align: center;
  background-color: black;
  padding: 2px 16px;
  color: white;
}

.demo {
  opacity: 0.6;
}

.active,
.demo:hover {
  opacity: 1;
}

img.w3-hover-sepia {
  transition: 0.3s
}

.w3-hover-sepia:hover {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)
}
</style>



<script>
function openModal() {
  document.getElementById('myModal').style.display = "block";
}

function closeModal() {
  document.getElementById('myModal').style.display = "none";
}

var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  var captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script>